# Generated by Django 2.2.4 on 2020-12-23 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_exam', '0002_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='author',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
